# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndo" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "8a5211412dd693fd2062531b4b5d9f16d917bf410c713c7be3efedc839a6bc76"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3448485d914a8cdacc1db78edc2167067bbe1dd40caa4305fb33bfeef5ffdd98"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1db7035c0b254be804b5d9d90059f72e4135340d3b0a9444cb13d7f1eb24481e"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "499b0d7c9c14385f347afb5fc36af14e715043eb8d12c4fcf5854da99609d3d2"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ndo"
  desc "A CLI-first task runner: add recipes from the CLI, layer central and local recipe sets, and bind positional arguments naturally."
  homepage "https://github.com/green-threads/ndo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndo"]
    end
  end

  # No zap stanza required

end
