# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndo" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "491450f5b8a7f97fb27ce2b2517de594fdc2e81f9561c51de72e09fa5b61e616"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00508b636ddef4a3732c729f44996db641f390c973735471a667ea4b8b8f77f2"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "019a2690196e5c76de280de6348b266a2463ad7dd8b38685d138f16d07a3b27c"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eedc1adc08ebca7cb2e9df9301eab88297717da715e8bd1a02bb587eebbe2c8f"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ndo"
  desc "A CLI-first task runner: add recipes from the CLI, layer central and local recipe sets, and bind positional arguments naturally."
  homepage "https://github.com/green-threads/ndo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndo"]
    end
  end

  # No zap stanza required

end
