# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndo" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "250f00416e44b12105ff0807013321ee78d00a444148723d6804aa0bc9a912c7"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d89870bbadfb26678c4d7f77e048fef9798a6314a297cfb54de929047f96b634"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9afb82952df86580e45a096a5689da75518866589ce49c19256802c1adde6ba6"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad09dd3179bb0f8d665538029f3f0f6553311585b5c1ef994cb2fe53bafdda5e"
      url "https://github.com/green-threads/ndo/releases/download/v#{version}/ndo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ndo"
  desc "A CLI-first task runner: add recipes from the CLI, layer central and local recipe sets, and bind positional arguments naturally."
  homepage "https://github.com/green-threads/ndo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndo"]
    end
  end

  # No zap stanza required

end
